# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    mysql-deployment.yml                               :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dnakano <dnakano@student.42tokyo.jp>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/11/20 18:52:08 by dnakano           #+#    #+#              #
#    Updated: 2020/12/02 09:48:51 by dnakano          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-pvc
      containers:
      - name: mysql
        image: ft_services/mysql
        imagePullPolicy: Never
        volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping", "-u", "\"$DB_ROOTUSER\"", "--password=\"$DB_ROOTPASS\""]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
