# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    grafana-deployment.yml                             :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dnakano <dnakano@student.42tokyo.jp>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/11/20 18:52:08 by dnakano           #+#    #+#              #
#    Updated: 2020/11/25 19:00:51 by dnakano          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: ft_services/grafana
        imagePullPolicy: Never
