# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    grafana-deployment.yml                             :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dnakano <dnakano@student.42tokyo.jp>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/11/20 18:52:08 by dnakano           #+#    #+#              #
#    Updated: 2020/12/02 20:10:17 by dnakano          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: ft_services/grafana
        imagePullPolicy: Never
        env:
        - name: INFDB_GRAFANA_USER
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: infdb_grafana_user
        - name: INFDB_GRAFANA_PASS
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: infdb_grafana_pass
        - name: INFDB_TELEGRAF_USER
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: infdb_telegraf_user
        - name: INFDB_TELEGRAF_PASS
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: infdb_telegraf_pass
