# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    grafana-service.yml                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dnakano <dnakano@student.42tokyo.jp>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/11/20 19:18:10 by dnakano           #+#    #+#              #
#    Updated: 2020/11/25 19:20:42 by dnakano          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  name: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.200
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
    name: https
    protocol: TCP
