# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    nginx-deployment.yml                               :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dnakano <dnakano@student.42tokyo.jp>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/11/20 18:52:08 by dnakano           #+#    #+#              #
#    Updated: 2020/12/05 00:57:20 by dnakano          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ft_services/nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
        livenessProbe:
          exec:
            command: ["/liveness.sh"]
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
        env:
        - name: INFDB_TELEGRAF_USER
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: infdb_telegraf_user
        - name: INFDB_TELEGRAF_PASS
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: infdb_telegraf_pass
        - name: SSH_LOGINTITLE
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: ssh_logintitle
        - name: SSHUSER
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: sshuser
        - name: SSHUSER_PASS
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: sshuser_pass
