# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    nginx-service.yml                                  :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dnakano <dnakano@student.42tokyo.jp>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/11/20 19:18:10 by dnakano           #+#    #+#              #
#    Updated: 2020/11/22 11:35:38 by dnakano          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.200
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    name: http
    protocol: TCP
  - port: 443
    targetPort: 443
    name: https
    protocol: TCP
  - port: 22
    targetPort: 22
    name: ssh
    protocol: TCP
