# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    phpmyadmin-service.yml                             :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dnakano <dnakano@student.42tokyo.jp>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/11/20 19:18:10 by dnakano           #+#    #+#              #
#    Updated: 2020/11/22 10:23:19 by dnakano          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
  - port: 5000
    targetPort: 5000
    name: https
    protocol: TCP
