# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    wordpress-deployment.yml                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dnakano <dnakano@student.42tokyo.jp>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/11/20 18:52:08 by dnakano           #+#    #+#              #
#    Updated: 2020/12/05 00:57:33 by dnakano          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: ft_services/wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
        livenessProbe:
          httpGet:
            path: /health/
            port: 5050
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 15
        env:
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: mysql_host
        - name: WP_MYSQLDBNAME
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: wp_mysqldbname
        - name: WP_MYSQLUSER
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: wp_mysqluser
        - name: WP_MYSQLPASS
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: wp_mysqlpass
        - name: INFDB_TELEGRAF_USER
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: infdb_telegraf_user
        - name: INFDB_TELEGRAF_PASS
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: infdb_telegraf_pass
        - name: WP_ADMIN_NAME
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: wp_admin_name
        - name: WP_ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: wp_admin_email
        - name: WP_ADMIN_PASS
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: wp_admin_pass
        - name: WP_USER1_NAME
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: wp_user1_name
        - name: WP_USER1_EMAIL
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: wp_user1_email
        - name: WP_USER1_PASS
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: wp_user1_pass
        - name: WP_USER2_NAME
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: wp_user2_name
        - name: WP_USER2_EMAIL
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: wp_user2_email
        - name: WP_USER2_PASS
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: wp_user2_pass
