# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    ftps-deployment.yml                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dnakano <dnakano@student.42tokyo.jp>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/11/21 08:02:32 by dnakano           #+#    #+#              #
#    Updated: 2020/12/02 20:03:04 by dnakano          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deploy
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ft_services/ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 60000
        - containerPort: 60001
        - containerPort: 60002
        - containerPort: 60003
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 10
          tcpSocket:
            port: 21
        env:
        - name: INFDB_TELEGRAF_USER
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: infdb_telegraf_user
        - name: INFDB_TELEGRAF_PASS
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: infdb_telegraf_pass
        - name: FTP_USER
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: ftp_user
        - name: FTP_USER_PASS
          valueFrom:
            secretKeyRef:
              name: ft-services-secret
              key: ftp_user_pass
