# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    ftps-deployment.yml                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dnakano <dnakano@student.42tokyo.jp>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/11/21 08:02:32 by dnakano           #+#    #+#              #
#    Updated: 2020/11/21 08:02:34 by dnakano          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deploy
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ft_services/ftps
        imagePullPolicy: Never
